### ISSUE TITLE
admin的账号密码忘了怎么办

### ISSUE THREAD

**Issue by mbbsm** [sduoduo233/telegram-push#4]
admin的账号密码忘了怎么办

**Comment by sduoduo233** [comment]
账号是admin，密码可以在cloudflare kv查看

![2023-05-10_20-35](https://github.com/sduoduo233/telegram-push/assets/85996970/854e8efd-77cd-46c5-a79b-527f003c99c5)
![2023-05-10_20-38](https://github.com/sduoduo233/telegram-push/assets/85996970/b83f724d-08cd-4bee-89ad-6a02716594f3)
