### ISSUE TITLE
curl -s -X POST 用这个咋填写呢

### ISSUE THREAD

**Issue by jiangbeth** [sduoduo233/telegram-push#5]
curl -s -X POST "https://api.telegram.org/bot<token>/sendMessage" -d chat_id=你的ID -d text="消息"

**Comment by sduoduo233** [comment]
这个项目和telegram官方的api是不一样的，curl的用法可以看这张图

https://raw.githubusercontent.com/sduoduo233/telegram-push/master/images/13.png

**Comment by jiangbeth** [comment]
谢谢
